version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ..
        target: /opt/web2py/applications/OZtree
        consistency: cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:db

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: OneZoom
      MYSQL_USER: oz
      MYSQL_PASSWORD: passwd

    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MySQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
